[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["echo_service_nr"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "echo_service_nr"
  org = "cchpdp"
  version = "3.1.1"

